//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AulaCsharp
    {
        public int Id { get; set; }
        public string Aluno { get; set; }
        public Nullable<int> Idade { get; set; }
        public bool Ativo { get; set; }
        public int UsuInc { get; set; }
        public int UsuAlt { get; set; }
        public System.DateTime Datinc { get; set; }
        public System.DateTime DatAlt { get; set; }
    }
}
