//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aulacsharpEntities : DbContext
    {
        public aulacsharpEntities()
            : base("name=aulacsharpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aluno> Alunos { get; set; }
        public virtual DbSet<AulaCsharp> AulaCsharps { get; set; }
        public virtual DbSet<Diario> Diarios { get; set; }
        public virtual DbSet<Doginho> Doginhoes { get; set; }
        public virtual DbSet<NotaAluno> NotaAlunos { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<VendasCarro> VendasCarros { get; set; }
    }
}
