//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendasCarro
    {
        public int Id { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Vendas { get; set; }
        public Nullable<System.DateTime> DataVenda { get; set; }
    }
}
