//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesingView.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivroAutor
    {
        public int Livro { get; set; }
        public int Autor { get; set; }
    }
}
