//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesingView.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livros()
        {
            this.Locacao = new HashSet<Locacao>();
            this.Autores = new HashSet<Autores>();
        }
    
        public int Id { get; set; }
        public int Registro { get; set; }
        public string Titulo { get; set; }
        public string Isbn { get; set; }
        public string Sinopse { get; set; }
        public string Observacoes { get; set; }
        public bool Ativo { get; set; }
        public System.DateTime DatInc { get; set; }
        public System.DateTime DatAlt { get; set; }
    
        public virtual Editoras Editoras { get; set; }
        public virtual Generos Generos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locacao> Locacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autores> Autores { get; set; }
    }
}
