//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesingView.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public int Id { get; set; }
        public int Registro { get; set; }
        public string Titulo { get; set; }
        public string Isbn { get; set; }
        public int Genero { get; set; }
        public int Editora { get; set; }
        public string Sinopse { get; set; }
        public string Observacoes { get; set; }
        public bool Ativo { get; set; }
        public int UsuInc { get; set; }
        public int UsuAlt { get; set; }
        public System.DateTime DatInc { get; set; }
        public System.DateTime DatAlt { get; set; }
    
        public virtual Editora Editora1 { get; set; }
        public virtual Genero Genero1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
