CREATE TABLE [dbo].[Usuarios]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Nome] VARCHAR(100) NOT NULL,
	[Login] VARCHAR(50) NOT NULL,
	[Senha] VARCHAR(50) NOT NULL,
	[Email] VARCHAR(100) NOT NULL,
	[Ativo] BIT NOT NULL,
	[UsuInc] INT NOT NULL,
	[UsuAlt] INT NOT NULL,
	[DatInc] DATETIME NOT NULL DEFAULT GETDATE(),
	[DatAlt] DATETIME NOT NULL DEFAULT GETDATE()
)
