//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesingView.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locacao
    {
        public int Id { get; set; }
        public int Tipo { get; set; }
        public System.DateTime Devolucao { get; set; }
        public bool Ativo { get; set; }
        public System.DateTime DatInc { get; set; }
        public System.DateTime DatAlt { get; set; }
    
        public virtual Livros Livros { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
