//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFisrtListGuy.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaBibliotecaDBEntities : DbContext
    {
        public SistemaBibliotecaDBEntities()
            : base("name=SistemaBibliotecaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autore> Autores { get; set; }
        public virtual DbSet<Editora> Editoras { get; set; }
        public virtual DbSet<Genero> Generos { get; set; }
        public virtual DbSet<Livro> Livros { get; set; }
        public virtual DbSet<Locacao> Locacaos { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
